---
- hosts: localhost
  become: true

- name: playbook - install packages
  import_playbook: playbooks/packages.yml

- name: playbook - configure system
  import_playbook: playbooks/configure.yml

- name: playbook - add dotfiles
  import_playbook: playbooks/dotfiles.yml

- name: playbook - add keybindings
  import_playbook: playbooks/keybindings.yml
