---
- hosts: localhost
  become: yes
  vars:
    bw_gpg_itemid: 04b938f4-0034-4986-bce1-ae23015bab3c # Bitwarden item id for GPG secret


  tasks:
    #########
    ## GPG ##
    #########

    # Fetch from bitwarden
    - name: Check if Bitwarden vault is unlocked
      command: bw status
      register: bw_status
      failed_when: '"unlocked" not in bw_status.stdout'
      become_user: fredrick

    - name: Get password from Bitwarden
      command: "bw get password {{ bw_gpg_itemid }} {{ attachment }} --raw"
      vars:
        attachment: private.pgp
      register: gpg_password
      become_user: fredrick

    - name: Get privatekey from Bitwarden
      command: "bw get attachment --itemid {{ bw_gpg_itemid }} {{ attachment }} --raw"
      vars:
        attachment: private.pgp
      register: gpg_key_private
      become_user: fredrick

    - name: Get publickey from Bitwarden
      command: "bw get attachment --itemid {{ bw_gpg_itemid }} {{ attachment }} --raw"
      vars:
        attachment: public.pgp
      register: gpg_key_public
      become_user: fredrick

    - name: Get ownertrust from Bitwarden
      command: "bw get attachment --itemid {{ bw_gpg_itemid }} {{ attachment }} --raw"
      vars:
        attachment: ownertrust.txt
      register: gpg_ownertrust
      become_user: fredrick

    # Import to GPG
    - name: import private key
      args:
        stdin: "{{ gpg_key_private.stdout }}"
      command: gpg --passphrase {{ gpg_password.stdout }} --pinentry-mode loopback --import -
      become_user: fredrick

    - name: import public key
      args:
        stdin: "{{ gpg_key_public.stdout }}"
      command: gpg --import -
      become_user: fredrick

    - name: import ownertrust
      args:
        stdin: "{{ gpg_ownertrust.stdout }}"
      command: gpg --import-ownertrust -
      become_user: fredrick
