---
- hosts: localhost
  become: yes
  vars:
    GRUB_CMD_LINE: mem_sleep_default=deep

  tasks:
    - name: Check if grub cmdlines exists
      shell: grep GRUB_CMDLINE_LINUX_DEFAULT /etc/default/grub | grep -c "{{ GRUB_CMD_LINE }}"
      register: cgroup_status
      ignore_errors: true

    - name: Append grub cmdlines
      lineinfile: dest="/etc/default/grub" regexp='GRUB_CMDLINE_LINUX_DEFAULT="(.*)"' line='GRUB_CMDLINE_LINUX_DEFAULT="\1 {{ GRUB_CMD_LINE }}"' backrefs=yes
      when: cgroup_status.stdout == "0"

    - name: Update grub
      shell: update-grub2
      when: cgroup_status.stdout == "0"

    # - name: reboot if we need it
    #   shell: sleep 2 && shutdown -r now "Ansible updates triggered"
    #   async: 1 
    #   poll: 0
    #   ignore_errors: true
    #   when: cgroup_status.stdout == "0"

    # - name: waiting for server to come back
    #   local_action: wait_for host={{ansible_fqdn}} state=started timeout=600 delay=15
    #   sudo: false
    #   when: cgroup_status.stdout == "0"

# To verify deep sleep run
# cat /sys/power/mem_sleep
# should now output "s2idle [deep]"
