---
- hosts: localhost
  become: true
  tasks:
    ##########
    ## Brew ##
    ##########

    - name: shell - check if brew is present
      command: brew -v
      register: brew_present
      ignore_errors: true

    - name: shell - install brew
      shell: /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"
      when: brew_present is failed

    - name: brew - cli tools
      homebrew:
        name:
          - bat
          - tmux
          - zsh
        state: present

    ##########
    ## asdf ##
    ##########

    - name: asdf - clone asdf repository
      git:
        repo: "https://github.com/asdf-vm/asdf.git"
        dest: "~/.asdf"
        version: v0.11.3
        update: no
        accept_hostkey: yes
      become_user: fredrick

    - name: asdf - add, install and set global versions
      shell: . $HOME/.asdf/asdf.sh && asdf plugin add "{{ item }}" && asdf install "{{ item }}" latest && asdf global "{{ item }}" latest
      args:
        executable: /usr/bin/zsh
      with_items:
        - air
        - argo
        - argo-rollouts
        - argocd
        - awscli
        - direnv
        - gcloud
        - github-cli
        - golang
        - helm
        - istioctl
        - kompose
        - krew
        - kubectl
        - operator-sdk
        - pulumi
        - stern
        - terraform
        - terraform-docs
        - yq
      register: asdf_add_result
      failed_when:
        - asdf_add_result.rc == 1 or asdf_add_result.rc == 2 and not "'already added' in asdf_add_result.stderr" # Already added plugin should be rc0..
      become_user: fredrick

    - name: asdf - configure direnv
      shell: ~/.asdf/bin/asdf direnv setup --shell zsh --version latest
      become_user: fredrick
