---
- hosts: localhost
  become: true
  vars:
    local_user: fredrick

  tasks:
    ##########
    ## Brew ##
    ##########

    - name: shell - check if brew is present
      command: brew -v
      register: brew_present
      ignore_errors: true

    - name: shell - install brew
      shell: /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"
      when: brew_present is failed

    - name: brew - cli tools
      homebrew:
        name:
          # - awscli
          - coreutils
          - curl
          - ed
          - findutils
          - gawk
          - git
          - gnu-sed
          - gnu-tar
          - grep
          - koekeishiya/formulae/skhd
          - koekeishiya/formulae/yabai
          - make
          - parallel
          - tmux
          - zsh
        state: present
      become_user: "{{ local_user }}"

    - name: brew - gui tools
      homebrew_cask:
        name:
          - alacritty
          - discord
          - spaceid
          - slack
        state: present
      become_user: "{{ local_user }}"

    ##########
    ## asdf ##
    ##########

    - name: asdf - clone asdf repository
      git:
        repo: "https://github.com/asdf-vm/asdf.git"
        dest: "~/.asdf"
        version: v0.11.3
        update: no
        accept_hostkey: yes
      become_user: "{{ local_user }}"

    - name: asdf - add, install and set global versions
      shell: . $HOME/.asdf/asdf.sh && asdf plugin add "{{ item }}" && asdf install "{{ item }}" latest && asdf global "{{ item }}" latest
      loop:
        - air
        - argo
        - argo-rollouts
        - argocd
        - awscli
        - bat
        - direnv
        - gcloud
        - golang
        - helm
        - istioctl
        - jq
        - kompose
        - krew
        - kubectl
        - operator-sdk
        - pulumi
        - python
        - sops
        - stern
        - terraform
        - terraform-docs
        - yq
        # - github-cli # no arm64
      register: asdf_add_result
      failed_when:
        - asdf_add_result.rc == 1 or asdf_add_result.rc == 2 and not "'already added' in asdf_add_result.stderr" # Already added plugin should be rc0..
      become_user: "{{ local_user }}"

    - name: asdf - configure direnv
      shell: asdf direnv setup --shell zsh --version latest
      args:
        executable: /bin/zsh
      become_user: "{{ local_user }}"
