---
- hosts: localhost
  become: true

  tasks:
    ###########
    ## Shell ##
    ###########

    - name: shell - brew provided zsh as default shell
      shell: chsh -s /bin/zsh fredrick

    ################
    ## Containers ##
    ################

    - name: kubectl - create .kube directory
      file:
        path: $HOME/.kube
        state: directory
      become_user: fredrick

    - name: kubectl - touch config file
      file:
        path: $HOME/.kube/config
        state: touch
      become_user: fredrick

    # - name: docker - add user to docker group
    #   user: name=fredrick
    #     groups=docker
    #     append=yes

    # - name: docker - disable system services (for power savings)
    #   ansible.builtin.systemd:
    #     name: "{{ item }}"
    #     enabled: no
    #     masked: no
    #   become_user: root
    #   with_items:
    #     - docker.socket
    #     - docker.service
    #     - containerd.service
