---
- hosts: localhost
  become: yes
  tasks:
#    - name: add pipewire apt repository
#      ansible.builtin.apt_repository:
#        repo: ppa:pipewire-debian/pipewire-upstream
#        state: present

    - name: remove packages
      apt:
        name:
          - pipewire-media-session
          - pulseaudio-module-bluetooth
        state: absent
        purge: yes

    - name: install apt packages
      apt:
        update_cache: yes
        cache_valid_time: 3600
        pkg:
          - gstreamer1.0-pipewire
          - libspa-0.2-bluetooth
          - pipewire
          - pipewire-audio-client-libraries
          - wireplumber
          - libfdk-aac2
          - libldacbt-abr2
          - libldacbt-enc2
          - libopenaptx0

    - name: reload daemon after installing pipewire
      ansible.builtin.systemd:
        daemon_reload: yes
        scope: user
      become_user: fredrick

    - name: enable pipewire and pulse layer
      ansible.builtin.systemd:
        name: "{{ item }}"
        enabled: yes
        state: started
        scope: user
      become_user: fredrick
      with_items:
        - pipewire
        - pipewire-pulse
        - wireplumber.service
