---
- hosts: localhost
  become: true

  tasks:
    ###########
    ## Shell ##
    ###########

    - name: set zsh as default shell
      shell: chsh -s $(which zsh) fredrick

    ############
    ## Laptop ##
    ############

    # Enable GuC, and HuC
    # Disable GVT-g virtualization as it is incompatible with GuC
    # https://ask.fedoraproject.org/t/intel-graphics-best-practices-and-settings-for-hardware-acceleration/21119

    - name: gpu - enable i915 features
      ansible.builtin.blockinfile:
        path: /etc/modprobe.d/i915.conf
        block: |
          options i915 enable_guc=3
          options i915 enable_fbc=1
        create: yes

    - name: i915 - rebuild intramfs
      command: dracut --force

    # - name: mouse - thinkpad x1 carbon gen9 configs
    #   copy: src={{ item.src }} dest={{ item.dest }}
    #   with_items:
    #     - { src: './files/modprobe.d/blacklist-touchpad.conf', dest: '/etc/modprobe.d/blacklist-touchpad.conf' }
    #     #- { src: './files/libinput/99-custom-x1c.quirks', dest: '/usr/share/libinput/99-custom-x1c.quirks' }
    #     #- { src: './files/udev/99-trackpoint.rules', dest: '/etc/udev/rules.d/99-trackpoint.rules' }

    #################
    ## UI & Themes ##
    #################

    # - name: systemd - get current systemd default
    #   command: "systemctl get-default"
    #   changed_when: false
    #   register: systemdefault

    # - name: systemd - default to graphical target
    #   command: "systemctl set-default graphical.target"
    #   when: "'graphical' not in systemdefault.stdout"

    # - name: sddm - copy chili theme
    #   synchronize:
    #     src: ./files/sddm/themes/chili
    #     dest: /usr/share/sddm/themes

    # - name: sddm - override theme directory, set current theme
    #   ansible.builtin.blockinfile:
    #     path: /usr/lib/sddm/sddm.conf.d/x11.conf
    #     block: |
    #       [Theme]
    #       ThemeDir=/usr/share/sddm/themes
    #       Current=chili

    - name: git - download dracula gnome gtk theme
      ansible.builtin.git:
        repo: "https://github.com/dracula/gtk.git"
        dest: /usr/share/themes/dracula
        update: true

    - name: dconf - use dracula as gnome gtk theme
      community.general.dconf:
        key: "/org/gnome/desktop/interface/gtk-theme"
        value: "'dracula'"
        state: present
      become_user: fredrick

    - name: dconf - use papirus as gnome icon theme
      community.general.dconf:
        key: "/org/gnome/desktop/interface/icon-theme"
        value: "'Papirus'"
        state: present
      become_user: fredrick

    - name: dconf - disable all animations
      community.general.dconf:
        key: "/org/gnome/desktop/interface/enable-animations"
        value: "false"
        state: present
      become_user: fredrick

    - name: flatpak - allow themes folder in home
      command: sudo flatpak override --filesystem=$HOME/.themes
      become_user: fredrick

    - name: flatpak - set dracula as default theme
      command: sudo flatpak override --env=GTK_THEME=Dracula
      become_user: fredrick

    #############
    ## Systemd ##
    #############

    ## gnome-keyring-daemon
    # auto-login on session with ssh key support

    # - name: systemd - create systemd user service dir
    #   ansible.builtin.file:
    #     path: /home/fredrick/.config/systemd/user
    #     state: directory
    #   become_user: fredrick

    # - name: systemd - copy default gnome-keyring-daemon.service
    #   synchronize:
    #     dest: /home/fredrick/.config/systemd/user
    #     src: /usr/lib/systemd/user/gnome-keyring-daemon.service

    # - name: systemd - enable ssh on gnome-keyring-daemon.service
    #   ansible.builtin.replace:
    #     path: /usr/lib/systemd/user/gnome-keyring-daemon.service
    #     regexp: '"pkcs11,secrets"'
    #     replace: '"pkcs11,secrets,ssh"'

    # - name: systemd - override gnome-keyring service with pkcsl,ssh,secret components
    #   ansible.builtin.systemd:
    #     name: gnome-keyring-daemon
    #     state: started
    #     scope: user
    #     enabled: true
    #     daemon_reload: true
    #   become_user: fredrick

    # - name: pamd - unlock gnome-keyring during auth
    #   community.general.pamd:
    #     name: login
    #     type: auth
    #     control: include
    #     module_path: postlogin
    #     new_type: auth
    #     new_control: optional
    #     new_module_path: pam_gnome_keyring.so
    #     state: after

    # - name: pamd - update gnome-keyring password during password update
    #   community.general.pamd:
    #     name: login
    #     type: password
    #     control: include
    #     module_path: system-auth
    #     new_type: password
    #     new_control: optional
    #     new_module_path: pam_gnome_keyring.so
    #     state: after

    # - name: pamd - start gnome-keyring on new session
    #   community.general.pamd:
    #     name: login
    #     type: session
    #     control: include
    #     module_path: postlogin
    #     new_type: session
    #     new_control: optional
    #     new_module_path: pam_gnome_keyring.so
    #     module_arguments: 'auto_start'
    #     state: after

    ############
    ## Docker ##
    ############

    - name: docker - add user to docker group
      user: name=fredrick
        groups=docker
        append=yes

    - name: docker - disable system services (for power savings)
      ansible.builtin.systemd:
        name: "{{ item }}"
        enabled: no
        masked: no
      become_user: root
      with_items:
        - docker.socket
        - docker.service
        - containerd.service
