---
- hosts: localhost
  become: yes
  become_user: fredrick
  vars:
    profiles:
      - Personal
      - Sonat
      - Entur
  tasks:
  - name: firefox - get all profiles in folder
    args:
      chdir: "~/.mozilla/firefox"
    command: ls -d */ | grep -v "Crash Reports" | grep -v "Pending Pings"
    register: get_profiles

  - name: firefox - check if profiles are already created
    args:
      chdir: "~/.mozilla/firefox"
    command: ls -d */ | grep -v "Crash Reports" | grep -v "Pending Pings"
    register: get_profiles

  - name: firefox - create profiles
    args:
      chdir: "~/.mozilla/firefox"
    command: cp -r {{ firefox_path.stdout }}/ {{ firefox_id.stdout }}.{{ item }}
    with_items:
      - work
      - home

  - name: replace profile default name with work
    lineinfile:
      path: ~/.mozilla/firefox/profiles.ini
      regexp: 'Name=default$'
      line: Name=work

  - name: replace profile default path with work
    lineinfile:
      path: ~/.mozilla/firefox/profiles.ini
      regexp: 'Path=.*default$'
      line: Path={{ firefox_id.stdout }}.work

  - name: replace profile default-release name with home
    lineinfile:
      path: ~/.mozilla/firefox/profiles.ini
      regexp: 'Name=default-release$'
      line: Name=home

  - name: replace profile default-release path with home
    lineinfile:
      path: ~/.mozilla/firefox/profiles.ini
      regexp: 'Path=.*default-release$'
      line: 'Path={{ firefox_id.stdout }}.home'

  - name: disable start last profile
    lineinfile:
      path: ~/.mozilla/firefox/profiles.ini
      regexp: '^StartWithLastProfile=.*'
      line: StartWithLastProfile=0

  - name: delete unused default folders
    args:
      chdir: "~/.mozilla/firefox"
    shell: |
      default_folders=`ls | grep default`
      rm -rf $default_folders

  - name: create chrome folder in profiles
    command: mkdir ~/.mozilla/firefox/{{ firefox_id.stdout }}.{{ item }}/chrome
    with_items:
      - work
      - home

  - name: copy files to profiles
    copy: src={{ item.src }} dest={{ item.dest }}
    with_items:
      - { src: './files/firefox/userChrome.css', dest: '~/.mozilla/firefox/{{ firefox_id.stdout }}.work/chrome/userChrome.css' }
      - { src: './files/firefox/userChrome.css', dest: '~/.mozilla/firefox/{{ firefox_id.stdout }}.home/chrome/userChrome.css' }
      - { src: './files/firefox/user.js', dest: '~/.mozilla/firefox/{{ firefox_id.stdout }}.work/user.js' }
      - { src: './files/firefox/user.js', dest: '~/.mozilla/firefox/{{ firefox_id.stdout }}.home/user.js' }
