---
- hosts: localhost
  become: true
  become_user: fredrick

  tasks:
    ################################
    # Remove Existing Keybindings ##
    ################################

    - name: dconf - dump org.gnome.desktop.wm.keybindings
      shell: gsettings list-recursively | fgrep org.gnome.desktop.wm.keybindings | awk '{print $2}'
      register: existing_keybindings_1

    - name: dconf - remove all keybindings in org.gnome.desktop.wm.keybindings
      community.general.dconf:
        key: "/org/gnome/desktop/wm/keybindings/{{ item }}"
        value: "['']"
        state: present
      with_items: "{{ existing_keybindings_1.stdout_lines }}"

    - name: dconf - dump org.gnome.shell.keybindings
      shell: gsettings list-recursively | fgrep org.gnome.shell.keybindings | awk '{print $2}'
      register: existing_keybindings_2

    - name: dconf - remove all keybindings in org.gnome.shell.keybindings
      community.general.dconf:
        key: "/org/gnome/shell/keybindings/{{ item }}"
        value: "['']"
        state: present
      with_items: "{{ existing_keybindings_2.stdout_lines }}"

    - name: dconf - dump org.freedesktop.ibus.general.hotkey
      shell: gsettings list-recursively | fgrep org.freedesktop.ibus.general.hotkey | awk '{print $2}'
      register: existing_keybindings_3

    - name: dconf - remove all keybindings in org.freedesktop.ibus.general.hotkey
      community.general.dconf:
        key: "/org/freedesktop/ibus/general/hotkey/{{ item }}"
        value: "['']"
        state: present
      with_items: "{{ existing_keybindings_3.stdout_lines }}"

    - name: dconf - dump org.gnome.mutter.keybindings
      shell: gsettings list-recursively | fgrep org.gnome.mutter.keybindings | awk '{print $2}'
      register: existing_keybindings_4

    - name: dconf - remove all keybindings in org.gnome.mutter.keybindings
      community.general.dconf:
        key: "/org/gnome/mutter/keybindings/{{ item }}"
        value: "['']"
        state: present
      with_items: "{{ existing_keybindings_4.stdout_lines }}"

    - name: dconf - dump org.gnome.shell.extensions.dash-to-dock
      shell: gsettings list-recursively | fgrep 'org.gnome.shell.extensions.dash-to-dock app-' | awk '{print $2}'
      register: existing_keybindings_5

    - name: dconf - remove all keybindings in org.gnome.shell.extensions.dash-to-dock
      community.general.dconf:
        key: "/org/gnome/shell/extensions/dash-to-dock/{{ item }}"
        value: "['']"
        state: present
      with_items: "{{ existing_keybindings_5.stdout_lines }}"

    - name: dconf - dump org.gnome.mutter.wayland.keybindings
      shell: gsettings list-recursively | fgrep org.gnome.mutter.wayland.keybindings | awk '{print $2}'
      register: existing_keybindings_6

    - name: dconf - remove all keybindings in org.gnome.mutter.wayland.keybindings
      community.general.dconf:
        key: "/org/gnome/mutter/wayland/keybindings/{{ item }}"
        value: "['']"
        state: present
      with_items: "{{ existing_keybindings_6.stdout_lines }}"

    - name: dconf - replace specific keybinding entries in dconf with empty string
      community.general.dconf:
        key: "{{ item }}"
        value: "''"
        state: present
      with_items:
        - /org/gnome/mutter/overlay-key

    - name: dconf - replace specific keybinding entries in dconf with empty list of string
      community.general.dconf:
        key: "{{ item }}"
        value: "['']"
        state: present
      with_items:
        - /org/gnome/settings-daemon/plugins/media-keys/email
        - /org/gnome/settings-daemon/plugins/media-keys/help
        - /org/gnome/settings-daemon/plugins/media-keys/magnifier
        - /org/gnome/settings-daemon/plugins/media-keys/magnifier-zoom-in
        - /org/gnome/settings-daemon/plugins/media-keys/magnifier-zoom-out
        - /org/gnome/settings-daemon/plugins/media-keys/screenreader
        - /org/gnome/settings-daemon/plugins/media-keys/screensaver
        - /org/gnome/settings-daemon/plugins/media-keys/search
        - /org/gnome/settings-daemon/plugins/media-keys/www
        - /org/gnome/shell/extensions/dash-to-dock/shortcut-text
        - /org/gnome/shell/extensions/pop-shell/activate-launcher
        - /org/gnome/shell/extensions/pop-shell/pop-monitor-down
        - /org/gnome/shell/extensions/pop-shell/pop-monitor-left
        - /org/gnome/shell/extensions/pop-shell/pop-monitor-right
        - /org/gnome/shell/extensions/pop-shell/pop-monitor-up
        - /org/gnome/shell/extensions/pop-shell/pop-workspace-down
        - /org/gnome/shell/extensions/pop-shell/pop-workspace-up
        - /org/gnome/shell/extensions/pop-shell/tile-move-up-global
        - /org/gnome/shell/extensions/pop-shell/tile-move-down-global
        - /org/gnome/shell/extensions/pop-shell/tile-move-left-global
        - /org/gnome/shell/extensions/pop-shell/tile-move-right-global

    ########################
    ## Create Keybindings ##
    ########################

    # For listing out possible keys to rebinds, run this command:
    # cat /usr/share/X11/xkb/rules/base.lst

    - name: dconf - modifier key bindings
      community.general.dconf:
        key: "{{ item.path }}"
        value: "{{ item.value }}"
        state: present
      with_items:
        - path: /org/gnome/desktop/input-sources/xkb-options
          value: "['caps:super']"

    - name: dconf - window manager key bindings
      community.general.dconf:
        key: "{{ item.path }}"
        value: "{{ item.value }}"
        state: present
      with_items:
        - path: /org/gnome/settings-daemon/plugins/media-keys/search
          value: "['<Super>space']"
        - path: /org/gnome/desktop/wm/keybindings/close
          value: "['<Shift><Super>q']"
        - path: /org/gnome/desktop/wm/keybindings/toggle-fullscreen
          value: "['<Super>f']"
        - path: /org/gnome/desktop/wm/keybindings/switch-to-workspace-1
          value: "['<Super>1']"
        - path: /org/gnome/desktop/wm/keybindings/switch-to-workspace-2
          value: "['<Super>2']"
        - path: /org/gnome/desktop/wm/keybindings/switch-to-workspace-3
          value: "['<Super>3']"
        - path: /org/gnome/desktop/wm/keybindings/switch-to-workspace-4
          value: "['<Super>4']"
        - path: /org/gnome/desktop/wm/keybindings/switch-to-workspace-5
          value: "['<Super>5']"
        - path: /org/gnome/desktop/wm/keybindings/switch-to-workspace-6
          value: "['<Super>6']"
        - path: /org/gnome/desktop/wm/keybindings/switch-to-workspace-7
          value: "['<Super>7']"
        - path: /org/gnome/desktop/wm/keybindings/switch-to-workspace-8
          value: "['<Super>8']"
        - path: /org/gnome/desktop/wm/keybindings/switch-to-workspace-9
          value: "['<Super>9']"
        - path: /org/gnome/desktop/wm/keybindings/switch-to-workspace-10
          value: "['<Super>0']"
        - path: /org/gnome/desktop/wm/keybindings/switch-to-workspace-11
          value: "['<Super>minus']"
        - path: /org/gnome/desktop/wm/keybindings/switch-to-workspace-12
          value: "['<Super>equal']"
        - path: /org/gnome/desktop/wm/keybindings/switch-to-workspace-up
          value: "['<Control><Super>Up']"
        - path: /org/gnome/desktop/wm/keybindings/switch-to-workspace-left
          value: "['<Control><Super>Left']"
        - path: /org/gnome/desktop/wm/keybindings/switch-to-workspace-right
          value: "['<Control><Super>Right']"
        - path: /org/gnome/desktop/wm/keybindings/switch-to-workspace-down
          value: "['<Control><Super>Down']"
        - path: /org/gnome/desktop/wm/keybindings/move-to-workspace-1
          value: "['<Shift><Super>exclam']"
        - path: /org/gnome/desktop/wm/keybindings/move-to-workspace-2
          value: "['<Shift><Super>at']"
        - path: /org/gnome/desktop/wm/keybindings/move-to-workspace-3
          value: "['<Shift><Super>numbersign']"
        - path: /org/gnome/desktop/wm/keybindings/move-to-workspace-4
          value: "['<Shift><Super>dollar']"
        - path: /org/gnome/desktop/wm/keybindings/move-to-workspace-5
          value: "['<Shift><Super>percent']"
        - path: /org/gnome/desktop/wm/keybindings/move-to-workspace-6
          value: "['<Shift><Super>asciicircum']"
        - path: /org/gnome/desktop/wm/keybindings/move-to-workspace-7
          value: "['<Shift><Super>ampersand']"
        - path: /org/gnome/desktop/wm/keybindings/move-to-workspace-8
          value: "['<Shift><Super>asterisk']"
        - path: /org/gnome/desktop/wm/keybindings/move-to-workspace-9
          value: "['<Shift><Super>parenleft']"
        - path: /org/gnome/desktop/wm/keybindings/move-to-workspace-10
          value: "['<Shift><Super>parenright']"
        - path: /org/gnome/desktop/wm/keybindings/move-to-workspace-11
          value: "['<Shift><Super>underscore']"
        - path: /org/gnome/desktop/wm/keybindings/move-to-workspace-12
          value: "['<Shift><Super>plus']"
        - path: /org/gnome/desktop/wm/keybindings/move-to-workspace-up
          value: "['<Shift><Super>Up']"
        - path: /org/gnome/desktop/wm/keybindings/move-to-workspace-left
          value: "['<Shift><Super>Left']"
        - path: /org/gnome/desktop/wm/keybindings/move-to-workspace-right
          value: "['<Shift><Super>Right']"
        - path: /org/gnome/desktop/wm/keybindings/move-to-workspace-down
          value: "['<Shift><Super>Down']"

    - name: dconf - popos shell
      community.general.dconf:
        key: "{{ item.path }}"
        value: "{{ item.value }}"
        state: present
      with_items:
        - path: /org/gnome/shell/extensions/pop-shell/toggle-floating
          value: "['<Super><Shift>f']"
        - path: /org/gnome/shell/extensions/pop-shell/toggle-stacking-global
          value: "['<Super><Shift>s']"
        - path: /org/gnome/shell/extensions/pop-shell/toggle-tiling
          value: "['<Super><Shift>t']"
        - path: /org/gnome/shell/extensions/pop-shell/tile-orientation
          value: "['<Super><Shift>o']"

    - name: dconf - custom keybindings
      community.general.dconf:
        key: "{{ item.path }}"
        value: "{{ item.value }}"
        state: present
      with_items:
        - path: /org/gnome/settings-daemon/plugins/media-keys/custom-keybindings/custom0/name
          value: "'Launch - Browser'"
        - path: /org/gnome/settings-daemon/plugins/media-keys/custom-keybindings/custom0/command
          value: "'firefox -P'"
        - path: /org/gnome/settings-daemon/plugins/media-keys/custom-keybindings/custom0/binding
          value: "'<Shift><Super>Return'"
        - path: /org/gnome/settings-daemon/plugins/media-keys/custom-keybindings/custom1/name
          value: "'Launch - Terminal'"
        - path: /org/gnome/settings-daemon/plugins/media-keys/custom-keybindings/custom1/command
          value: "'alacritty'"
        - path: /org/gnome/settings-daemon/plugins/media-keys/custom-keybindings/custom1/binding
          value: "'<Shift><Super>space'"
