---
- hosts: localhost
  become: true
  tasks:
    ##################
    ## RPM Packages ##
    ##################

    - name: dnf - upgrade latest
      dnf:
        name: "*"
        state: latest

    - name: dnf - import RPM fusion keys
      ansible.builtin.rpm_key:
        state: present
        key: "{{ item }}"
      with_items:
        - "https://rpmfusion.org/keys?action=AttachFile&do=get&target=RPM-GPG-KEY-rpmfusion-free-fedora-2020"
        - "https://rpmfusion.org/keys?action=AttachFile&do=get&target=RPM-GPG-KEY-rpmfusion-nonfree-fedora-2020"

    - name: dnf - add RPM Fusion free repository
      shell: dnf install -y {{ item }}
      with_items:
        - "https://download1.rpmfusion.org/free/fedora/rpmfusion-free-release-{{ansible_distribution_major_version}}.noarch.rpm"
        - "https://download1.rpmfusion.org/nonfree/fedora/rpmfusion-nonfree-release-{{ansible_distribution_major_version}}.noarch.rpm"

    - name: dnf - add docker repository
      shell: dnf config-manager -y --add-repo https://download.docker.com/linux/fedora/docker-ce.repo

    - name: copr - enable repositories
      community.general.copr:
        name: "{{ item }}"
        state: enabled
      with_items:
        - erikreider/SwayNotificationCenter

    - name: dnf - system
      dnf:
        name:
          - '@Core'
          - '@Standard'
          - '@System Tools'
          - ddcutil
          - fwupd
          - gamemode
          - golang-github-docker-credential-helpers-devel
          - power-profiles-daemon # powerprofilesctl
          - smartmontools
          - tlp
          - tlp-rdw
          - ufw

    - name: dnf - security
      dnf:
        name:
          - fprintd-pam
          - gnome-keyring-pam
          - lxqt-policykit
          - pinentry-gnome3
          - polkit

    - name: dnf - firmware & drivers
      dnf:
        name:
        - '@Hardware Support'
        - intel-gpu-tools
        - intel-media-driver
        - libva
        - libva-utils
        - mesa-dri-drivers

    - name: dnf - audio/video
      dnf:
        name:
          - '@multimedia'
          - blueman
          - gstreamer1-vaapi
          - light
          - pavucontrol
          - pavucontrol-qt
          - pipewire-codec-aptx
          - playerctl
          - pulseaudio-utils

    - name: dnf - networking
      dnf:
        name:
        - '@Common NetworkManager Submodules'
        - network-manager-applet
        - NetworkManager
        - NetworkManager-config-connectivity-fedora
        - NetworkManager-openvpn-gnome
        - wireguard-tools
        - samba
        - samba-common
        - samba-client

    - name: dnf - virtualization & containerization
      dnf:
        name:
          - '@Vagrant with libvirt support'
          - '@Virtualization'
          - containerd.io
          - docker-ce
          - docker-ce-cli
          - docker-compose-plugin

    - name: dnf - printers
      dnf:
        name:
        - '@Printing Support'
        - system-config-printer

    - name: dnf - fonts
      dnf:
        name:
        - '@Fonts'

    - name: dnf - sway
      dnf:
        name:
          - grim
          - kanshi
          - qt5-qtgraphicaleffects # sddm theme
          - qt5-qtquickcontrols
          - sddm
          - slurp
          - sway
          - swaybg
          - swayidle
          - swaylock
          - SwayNotificationCenter
          - waybar
          - wdisplays
          - wl-clipboard
          - wofi
          - xdg-desktop-portal-gtk
          - xdg-desktop-portal-wlr
          - xorg-x11-server-Xwayland

    - name: dnf - cli
      dnf:
        name:
          - bat
          - curl
          - docker-compose
          - git
          - gvfs-goa # google drive in gnome-files
          - gvfs-smb
          - htop
          - inxi
          - mc
          - pass
          - python3-pip
          - sshpass
          - tmux
          - wget
          - yamllint
          - zip
          - zsh

    - name: dnf - gui
      dnf:
        name:
          - alacritty
          - blueman
          - digikam # why not flatpak = https://github.com/flathub/org.kde.digikam/issues/17
          - eog
          - file-roller
          - file-roller-nautilus
          - firefox
          - flatpak
          - gnome-control-center
          - gnome-online-accounts
          - gnome-system-log
          - gnome-system-monitor
          - mpv
          - nautilus
          - peek
          - raw-thumbnailer
          - seahorse
          - steam-devices
          - yubikey-manager
        state: latest

    - name: dnf - themes
      dnf:
        name:
          - papirus-icon-theme

    #############
    ## FlatPak ##
    #############

    - name: flatpak - flathub repository
      community.general.flatpak_remote:
        name: flathub
        state: present
        flatpakrepo_url: https://dl.flathub.org/repo/flathub.flatpakrepo
        method: user
      become_user: fredrick

    - name: flatpak - install packages
      community.general.flatpak:
        name: "{{ item }}"
        state: present
        method: user
      become_user: fredrick
      with_items:
        - com.discordapp.Discord
        - com.github.tchx84.Flatseal
        - com.github.vikdevelop.photopea_app
        - com.github.wwmm.easyeffects
        - com.gitlab.newsflash
        - com.jgraph.drawio.desktop
        - com.prusa3d.PrusaSlicer
        - com.rawtherapee.RawTherapee
        - com.sweethome3d.Sweethome3d
        - com.valvesoftware.Steam
        - com.visualstudio.code
        - io.dbeaver.DBeaverCommunity
        - net.scribus.Scribus
        - net.scribus.Scribus
        - org.chromium.Chromium
        - org.darktable.Darktable
        - org.filmulator.Filmulator
        - org.remmina.Remmina
        - rest.insomnia.Insomnia
        - sh.cider.Cider
        # - org.kde.digikam

    ##########
    ## asdf ##
    ##########

    - name: asdf - clone asdf repository
      git:
        repo: "https://github.com/asdf-vm/asdf.git"
        dest: "~/.asdf"
        version: v0.10.2
        update: no
        accept_hostkey: yes
      become_user: fredrick

    - name: asdf - add, install and set global versions
      shell: . $HOME/.asdf/asdf.sh && asdf plugin add "{{ item }}" && asdf install "{{ item }}" latest && asdf global "{{ item }}" latest
      args:
        executable: /usr/bin/zsh
      with_items:
        - argo
        - argo-rollouts
        - argocd
        - direnv
        - gcloud
        - github-cli
        - golang
        - helm
        - istioctl
        - kompose
        - krew
        - kubectl
        - operator-sdk
        - pulumi
        - stern
        - terraform
        - terraform-docs
        - yq
      register: asdf_add_result
      failed_when:
        - asdf_add_result.rc == 1 or asdf_add_result.rc == 2 and not "'already added' in asdf_add_result.stderr" # Already added plugin should be rc0..
      become_user: fredrick
